"use client";

import { useState } from "react";
import { Copy, Check, Share2 } from "lucide-react";
import { Button } from "./ui/button";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "./ui/card";
import { Input } from "./ui/input";

export function ReferralLinkCard() {
  const [copied, setCopied] = useState(false);
  const referralLink = "https://x-aegis.app/ref/user_982x";

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(referralLink);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy link", err);
    }
  };

  return (
    <Card className="bg-card border-border overflow-hidden relative">
      <CardHeader>
        <div className="flex items-center gap-2 mb-1">
          <div className="w-8 h-8 bg-primary/10 rounded-lg flex items-center justify-center">
            <Share2 className="text-primary w-4 h-4" />
          </div>
          <CardTitle>Share Your Link</CardTitle>
        </div>
        <CardDescription>
          Invite your friends to X-Aegis and earn rewards on every deposit they make.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex flex-col sm:flex-row gap-2">
          <div className="relative flex-1">
            <label htmlFor="referral-link" className="sr-only">
              Your unique referral link
            </label>
            <Input
              id="referral-link"
              value={referralLink}
              readOnly
              className="pr-12 bg-muted/50 font-mono text-sm"
              aria-label="Your unique referral link"
              aria-describedby="referral-link-description referral-link-badge"
            />
            <div
              id="referral-link-badge"
              className="absolute right-0 top-0 h-full flex items-center pr-3 pointer-events-none"
            >
              <span className="text-[10px] text-muted-foreground font-bold uppercase tracking-wider">Unique</span>
            </div>
          </div>
          <Button
            onClick={handleCopy}
            variant={copied ? "default" : "secondary"}
            className="shrink-0 gap-2 min-w-[100px]"
            aria-label={copied ? "Referral link copied" : "Copy referral link"}
          >
            {copied ? (
              <>
                <Check className="w-4 h-4" />
                Copied
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy
              </>
            )}
          </Button>
        </div>
        <p id="referral-link-description" className="text-xs text-muted-foreground">
          Your referral fee is <span className="text-primary font-bold">1.5%</span> of all shield fees generated by your invitees.
        </p>
      </CardContent>
    </Card>
  );
}
